apiVersion: v1
kind: Service
metadata:
  name: streamlit-svc
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: streamlit=211125418324.dkr.ecr.ap-northeast-2.amazonaws.com/webservice:latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: 211125418324.dkr.ecr.ap-northeast-2.amazonaws.com/webservice:latest
        ports:
        - containerPort: 8501
        env:
        - name: AUTH0_APP_URL
          value: "http://a3120f294fe78438d9479baf19198313-1976181292.ap-northeast-2.elb.amazonaws.com"
        - name: HF_MODEL_API_SERVER_URL
          value: "http://hf-api-svc:8000/generate-text/"
        volumeMounts:
        - name: aws-credentials-volume
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-credentials-volume
        secret:
          secretName: aws-credentials
